spring:
  application:
    name: seedflowplus
  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

kakao:
  api:
    local-url: "https://dapi.kakao.com/v2/local/search/address.json"

google:
  gemini:
    api:
      url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"

ncpms:
  api:
    url: "http://ncpms.rda.go.kr/npmsAPI/service"

# --- 모니터링 (Actuator & Prometheus) 설정 ---
management:
  endpoints:
    web:
      exposure:
        # health와 prometheus 엔드포인트만 외부에 노출
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: monsoon-backend