spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

# 테스트를 위한 더미값
  data:
    redis:
      host: localhost
      port: 6379
      password:
  mail:
      host: localhost
      port: 587
      username: test
      password: test

  # JWT 관련 더미 설정
jwt:
    secret: KHXxMP9orpMgPBvTyJYuajPO6tqyej2zx7od31vITTs=
    access-token-expiration-ms: 3600000
    refresh-token-expiration-ms: 1209600000